# -*- coding: utf-8 -*-
"""Tarea6CamiloMartinezEstay.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YeGcNiYWhvC4vbcF40aRFqqn6DtGhTxO

La librería "pybind11" nos ayudará a traspasar de un lenguaje a otro.

1. Primero instalaremos pybind11
2. En el archivo CMakeList nos servirá para decirle al programa lo que debe hacer (compilación y creación de librería)
"""

!pip install pybind11

import pybind11
print(pybind11.get_cmake_dir() ) #Imprimir directorio

!pwd

! cd build

# Commented out IPython magic to ensure Python compatibility.
# %cd build

!cmake ..

!make

!ls

import sys
sys.path.append('/content/build')

import stl_bindings

#Creación de vectores para luego sumarlos

a = [1,2,3]
b = [2,3,4]

resultado = stl_bindings.sum_vectors(a,b)
print("La suma de los vectores es ", resultado)

"""Esta suma está siendo realizada en C++, para luego ser reescrita por la librería creada."""

stl_bindings.create_map() #Nos entregará un diccionario (Def en archivo.cpp)

stl_bindings.saludo()

import stl_bindings
print(stl_bindings.imprimir("Camilo Martínez Estay"))

